trigger: none
pr: none

parameters:
  - name: location
    default: eastus
    type: string
    values:
      - eastus
      - eastus2
      - westcentralus
      - westus
      - westus2
      - southcentralus
      - northeurope
      - westeurope

  - name: resourceGroupName
    default: WVD-RGP-ImageBuilder
    type: string

  - name: templateParametersFile
    type: string
    default: Templates/image-builder.params.tyler.json

stages:
  - stage: CreateImage
    displayName: Create Image Stage
    jobs:
      - job: CreateImageJob
        displayName: Create Image Job
        variables:
          imageTemplateName: WVD-AIB-Tyler-$(Build.BuildNumber)
        steps:
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: $(AzureConnectionName)
              resourceGroupName: ${{ parameters.resourceGroupName }}
              location: ${{ parameters.location }}
              templateLocation: Linked artifact
              csmFile: $(Pipeline.Workspace)/s/Templates/image-builder.json
              csmParametersFile: $(Pipeline.Workspace)/s/${{ parameters.templateParametersFile }}
              overrideParameters: -imageTemplateName $(imageTemplateName)